language: node_js
 
node_js:
 node

services:
  - mongodb

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - mongodb-3.2-precise

    packages:
      - g++-4.8
      - mongodb-org-server

install:
      -cd $TRAVIS_BUILD_DIR/react && npm install
      -cd $TRAVIS_BUILD_DIR/server && npm install

scripts:
      -cd $TRAVIS_BUILD_DIR/react && npm test
      -cd $TRAVIS_BUILD_DIR/server && npm test